### ISSUE TITLE
Feature request: fix particular armor pieces

### ISSUE THREAD

**Issue by alexreinking** [3dots/EROptimizer#1]
Some pieces of armor have special, unique enchantments. These are particularly common on helmets (e.g. Azur's Glintstone Crown). It would be a nice feature to be select a piece of armor that will be returned in all results, with the remaining slots left to optimize.

**Comment by 3dots** [comment]
Yeah, you can do that. There is an "Armor Sets" tab at the top menu bar. You can disable all head pieces (with 1 button click), then also have to manually disable the "None" piece, and last, you can enable only the head pieces you want the optimizer to use.

**Comment by alexreinking** [comment]
Thanks for getting back to me! The interface for doing so wasn't clear to me, but I'll give that a shot.
