### ISSUE TITLE
Wrong "Available Weight for Armor"

### ISSUE THREAD

**Issue by ragurney** [3dots/EROptimizer#3]
Thanks for such a great tool! I tried using it and ran into an issue where the "available weight for armor" was inaccurate. 

My settings:
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/15261525/180896829-7a20425a-1744-4964-8438-950a5a0921c1.png">

In actuality the available weight for armor should be 17.64.

**Comment by 3dots** [comment]
Agh, my github was set to send me email notifications to my old university email. Sorry for taking so long to respond. 
I'll take a look today.

**Comment by 3dots** [comment]
Any chance you can help me debug it from this?

![image](https://user-images.githubusercontent.com/6589306/184506081-01926e3c-526d-4114-b87a-f4f939a1313b.png)
![image](https://user-images.githubusercontent.com/6589306/184506087-6365eee8-9233-4e82-8678-f8d9e01c297d.png)

**Comment by 3dots** [comment]
Are you sure of your calculation?

![image](https://user-images.githubusercontent.com/6589306/184507243-88eb175e-702b-4b85-b12f-d8c231250fb4.png)

![image](https://user-images.githubusercontent.com/6589306/184507120-17af9d15-6f0f-4ac7-a464-174e1935c531.png)

99.8*0.6999 - 3.1 = 66.75.

66.75 - 23*2 = 20.75.

**Comment by 3dots** [comment]
The endurance you enter into the calculation is the "before any talismans".
The calculator adds the endurance bonus from scarseal in the background.

**Comment by 3dots** [comment]
I'll add a "no talismans" note in the endurance input label. Or have another input like "actual endurance".

**Comment by ragurney** [comment]
Ah that may have been the problem, sorry 😓 thanks for responding and for the tool. Super helpful for Elden ring noobs like me getting their Tarnished butts kicked.
