### ISSUE TITLE
Suggestion: easier way to use specific armor pieces

### ISSUE THREAD

**Issue by cridus** [3dots/EROptimizer#4]
Hello, thanks for this optimizer, it's very useful.  
One thing I think would benefit it would be a way to set specific armor pieces to use without having to disable every piece and then enable only the specific ones.  
  
One reason for this, is that for example I usually don't care much about what chest piece I'd have to use, except a few that I disable (the ugly fat ones for example). Though when it happens that I want to use a specific chest piece, I'd have to disable them all and then enable that specific one, but once I've done that, to restore the previous state of the filters I'd have to re-enable all the chest pieces and then manually disable the ones I don't like, once more.  
  
This would be tedious. The way I'm doing it right now is copying the value of the site's LocalStorage item before changing the filters and then re-setting it afterwards 😬  
  
Please take into consideration making a section to set what specific armor pieces to use in the 4 armor slots with dropdown lists, that override the other filters.  
Thank you.

**Comment by 3dots** [comment]
I have the "disable all chest pieces" etc. buttons on Armor Sets tab.
This is the second time someone uses armor pieces page for this though, so I will add the disable/enable all buttons there as well.
The armor pieces page was really an afterthought for users to be able to check individual armor piece data. But I always intended the sets page for enabling/disabling.

**Comment by cridus** [comment]
But the point is, if you disable all pieces of a type to set a specific one, when you want to go back you'll have to re-enable them all and then go and disable one by one the ones you usually don't want.  
If there was a separate section to specify what pieces to use in the 4 armor slots, without having to touch the filters, that problem wouldn't exist.

**Comment by 3dots** [comment]
Hmm. I am not sure I am understanding you.
The disables/enables get saved to browser local storage when you run the optimizer. So after that even if you refresh the page, it should have all you disables restored.

**Comment by 3dots** [comment]
Also, I am confused. If you want only a select few pieces, disable all, then reenable only the ones you want?
![image](https://user-images.githubusercontent.com/6589306/185717832-9389e981-709b-4eeb-bc39-7bd1a15edc81.png)

**Comment by cridus** [comment]
Yeah I think I'm not making myself clear.  
  
Let's say this: usually I keep these equips disabled because I don't like how they look:  
  
- bullgoat helmet  
- bullgoat armor  
- crucible axe armor  
- crucible tree armor  
- fire prelate armor  
- knight armor  
- lionel's armor  
- lionel's gauntlets  
- lionel's greaves  
- malformed dragon armor  
- malformed dragon greaves  
- omen helm  
- omen armor  
- omen gauntlets  
- omen greaves  
- veteran's armor  
  
These are the filters that I'd like to always be set.  
Now, let's say that, once, I want to use a specific torso armor piece. Let's say it's the Lord of Blood's Robe. I'd have to disable all the torso armor pieces and enable only that one. Ok.  
Now, if I want to go back to the previous filters, I'd have to re-enable all the torso pieces, and then manually go back and disable the following, one by one:  
  
- bullgoat armor  
- crucible axe armor  
- crucible tree armor  
- fire prelate armor  
- knight armor  
- lionel's armor  
- lionel's greaves  
- malformed dragon armor  
- omen armor  
- veteran's armor  
  
This would be tedious. Especially because I'm used to the old Mugenmonkey DS3 character planner where you can disable specific armor pieces but also specify which ones to use in each slot, which overrides the filters:  
  
![image](https://user-images.githubusercontent.com/12686907/185749318-048ec476-b82e-4dde-afe0-11149640c28a.png)
  
That way, you can force a specific armor piece in a slot without touching the filters.

**Comment by 3dots** [comment]
Oh, interesting. Yeah, I can implement that. Might take me a weekend or two.

**Comment by 3dots** [comment]
Coded and deployed:

![image](https://user-images.githubusercontent.com/6589306/187208266-6c2b8f92-b11b-4ff8-8daf-7c7a7601fa4a.png)

**Comment by cridus** [comment]
Thank you!
