### ISSUE TITLE
"Raging Wolf Armor (Altered)" has wrong poise and focus

### ISSUE THREAD

**Issue by cridus** [3dots/EROptimizer#5]
Fextralife had two errors in the page of the altered version of this armor. Both poise and focus were listed as if they were identical to the unaltered version of the armor.  
The correct poise value is 12 instead of 15 and the correct value of focus is 10 instead of 18.  
  
P.S. I've found another wrong item: the Crucible Greaves. They're registered as having 14 poise but they have 16.

**Comment by 3dots** [comment]
Fixed it on the wiki, ran the scraper and deployed. Data is fixed.
