### ISSUE TITLE
Patch 1.07 changed the poise of almost all pieces of armor

### ISSUE THREAD

**Issue by cridus** [3dots/EROptimizer#6]
As the title says. The poise values need to be updated.

**Comment by 3dots** [comment]
My data comes from scraping these 4 tables:
https://eldenring.wiki.fextralife.com/Helms
https://eldenring.wiki.fextralife.com/Chest+Armor
https://eldenring.wiki.fextralife.com/Gauntlets
https://eldenring.wiki.fextralife.com/Leg+Armor

I started the scrape process, but has the data there been updated already? I kind of doubt it.

I wish I could grab data directly from the game, but I'm a not powerful enough wizard :D.

**Comment by cridus** [comment]
I guess I can contribute to updating these pages.
  
Edit: I've corrected the only 1 helm that had the wrong poise value, all the others were already updated. I'll check the other armor pieces now.  
By the way, can you please remove the cut-content armor pieces from your optimizer?  
They are:  
  
- ragged set
- brave's set
- millicent's set
- deathbed smalls
- grass hair ornament
  
I don't know if they're all in the optimizer, but I've seen at least the brave's set.

**Comment by cridus** [comment]
Done, I've corrected all the wrong entries and updated the whole leg armor page, which wasn't updated yet.

**Comment by 3dots** [comment]
Thanks. I launched the scrape again. 
It takes a couple hours because I don't want to be banned by the spam protection, so I take random half min pauses.
(it takes long because i also establish armor set relationships so i have to scrape each set page too)

Ill publish those changes when that's done.

For the cut-content. I might get that excluded today, or maybe during the weekend.

**Comment by 3dots** [comment]
Deployed

**Comment by cridus** [comment]
Oh thank you, that was quick.
By the way, you said you also scrape the individual armor set pages too, right? I didn't update these. So if you get the poise values from there they might be wrong or not updated.

**Comment by 3dots** [comment]
Armors sets pages -> Lets me know what pieces belong to what armor set.
Helms/Chest/Gauntlets/Legs tables -> try to read data here first. If any piece of data is missing-> go to individual armor piece page.

**Comment by 3dots** [comment]
Removed the unobtainable pieces.

![image](https://user-images.githubusercontent.com/6589306/195989284-99e3ce0e-ea94-4f3b-bdf6-4c101e0791e7.png)

Wiki says there 559 pieces in the game, I have 560. Don't know what the discrepancy is. I removed the ones stated explicitly as unobtainable.

Anyway, deployed that.
